version: 2
jobs:
  build:
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-go
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo "hello world"